### ISSUE TITLE
Put a link on it

### ISSUE THREAD

**Issue by thien-do** [monodyle/typings-app#13]
Please put a link to the deployment.. I can't find the URL of your app

**Comment by monodyle** [comment]
Thanks, I will deploy it later when I finish the new upgrade. Just a migrate to svelte so it has a lot of work to do.

**Comment by monodyle** [comment]
I just deploy the project on vercel. You can check it out in https://typing-test-app.vercel.app/

Some feature currently doesn't support and currently using free API so maybe it took a long time to response your typing content.
